### ISSUE TITLE
Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by lukeclewlow** [zeppelin/ember-click-outside#1]
Hi there,

I'm getting the error 'Cannot read property 'bind' of undefined.'

I'm using the component as described in the readme. The component it is consumed in is only rendered after a user action, but I understood that the Ember.run in the component would make sure there was something to bind.

I don't think I fully understand what's going on with the binding so having trouble getting very far with this bug. Any pointers in the right direction would be massively appreciated! Has always worked great for me up till this point.

Thanks!

**Comment by zeppelin** [comment]
I'll look into it next week!

**Comment by zeppelin** [comment]
@lukeclewlow can you set up an example repo or a gist?

**Comment by JoshSmith** [comment]
@lukeclewlow was this resolved for you?

**Comment by begedin** [comment]
Is this happening in development or when running tests? PhantomJS doesn't support `Function.prototype.bind`, so that might be the problem. To get around that, usually adding https://github.com/pixelhandler/ember-cli-es5-shim to dev dependencies does the trick:

`npm install --save-dev ember-cli-es5-shim`

**Comment by lukeclewlow** [comment]
It's in development. I solved my issue by changing the bound function in the mixin to: 

`````
const bound = function(fnName) {
  return computed(fnName, function() {
    if(this.get(fnName)) {
      return this.get(fnName).bind(this);
    }
  });
};
`````
