### ISSUE TITLE
Close after change route

### ISSUE THREAD

**Issue by brunowego** [zeppelin/ember-click-outside#12]
I am trying close after change route, do you have a tip to do that? Thanks.

**Comment by zeppelin** [comment]
@brunowego Could you please explain further?

**Comment by brunowego** [comment]
In my app, after change to another route inside the dropdown, this dropdown stay open.

**Comment by zeppelin** [comment]
Ah, I see what you mean. Just make sure that clicking on links inside the menu also hides the dropdown, just like the outside click. Example: [user-menu component](https://github.com/code-corps/code-corps-ember/blob/c9dedb3819a586167943aaba3d0af88172c6f8da/app/components/user-menu.js), [user-menu template](https://github.com/code-corps/code-corps-ember/blob/ceaa2e1c00a4d56163577805584fdbc40d42f73f/app/templates/components/user-menu.hbs) from the Code Corps repo.

**Comment by brunowego** [comment]
Thanks for the tip!
