### ISSUE TITLE
Update add-on  to support "on" modifier

### ISSUE THREAD

**Issue by owzzz** [zeppelin/ember-click-outside#143]
With the Octane/Glimmer updates it would be great to see the `on` modifier supported going forward. I get template lint errors using the current `action` modifier.

**Error**
`error  Do not use `action` as (action ...). Instead, use the `on` modifier and `fn` helper.  no-action`

**On modifier example**
`{{on-click-outside (on "click" this.toggle)}}`

**Comment by zeppelin** [comment]
Hi @owzzz 👋 

This is not quite how modifiers work. You can, however, totally do
`{{on-click-outside this.toggle}}`
and make the error disappear.
