### ISSUE TITLE
Ember server fails complaining about missing browserify temp file

### ISSUE THREAD

**Issue by alecho** [zeppelin/ember-click-outside#23]
`broccoliBuilderErrorStack: Error: ENOENT: no such file or directory, open 'APP/tmp/source_map_concat-input_base_path-xpeM6EbX.tmp/browserify/browserify.js'`

I've narrowed the issue down to when I installed this addon. I've cleared node_modules, tmp, and dist and tried to build/serve and the error persists.

**Comment by zeppelin** [comment]
I'm using browserify to [import the `matches-selector` package](https://github.com/zeppelin/ember-click-outside/blob/2da21c3b0afea59cc79903edcb6c9e1d543f8c4e/addon/utils.js#L2), but I guess I have find a another solution, as I was able to reproduce the bug.

Looking into it!

**Comment by alecho** [comment]
Bummer. I was hoping it was on my end but I'm glad you were able to reproduce. Let me know if there's  anything I can help with.

**Comment by zeppelin** [comment]
@alecho Thanks for your patience. As a temporary solution, I'll probably just gonna copy-paste the module's content into my addon code, as it's not really much and has no dependency. It sucks that importing CJS is such a hassle in addon-land...

**Comment by zeppelin** [comment]
Should be fixed in `1.0.0-beta.3`

@courajs @alecho Thanks for reporting!
