### ISSUE TITLE
ember-click-outside dosent work in ie11

### ISSUE THREAD

**Issue by pabloascarza** [zeppelin/ember-click-outside#37]
Hi in the mixin.js

``  

    outsideClickHandler(e) {
    const element = get(this, 'element');

    // Check if the click target still is in the DOM.
    // If not, there is no way to know if it was inside the element or not.
    const isRemoved = !e.target || !document.contains(e.target);

    // Check the element is found as a parent of the click target.
    const isInside = element === e.target || element.contains(e.target);

    if (!isRemoved && !isInside) {
      this.clickOutside(e);
    }  },

the document.contains method is not defined in ie11 please add the fallback to document.body.contains

**Comment by zeppelin** [comment]
This should be fixed in #35. (Reported in #30, released in `1.0.0-beta.6`).
- Could you check which version are you using?

(Closing in the meantime)

**Comment by zeppelin** [comment]
Just use `1.0.0` and you should be good to go :)

**Comment by zeppelin** [comment]
@neeleshsaxena Ah, this bug seems to be haunting me for eternity :/

Will investigate soon...

**Comment by pabloascarza** [comment]
Hi i found a the solution for this problem in the mixin.js `
const documentOrBodyContains = (element) => {
  // https://github.com/zeppelin/ember-click-outside/issues/30
  if (typeof document.contains === 'function') {
    return document.contains(element);
  } else {
    document.body.contains(element);
  }
}`

You need to add a return like this

`
const documentOrBodyContains = (element) => {
  // https://github.com/zeppelin/ember-click-outside/issues/30
  if (typeof document.contains === 'function') {
    return document.contains(element);
  } else {
    return document.body.contains(element);
  }
}`

and it works can you pls update this i need this now :(

**Comment by zeppelin** [comment]
Sorry for noticing this a bit late, notifications from Github is still not that great. Will update this sometime in the next couple days.

**Comment by zeppelin** [comment]
Fixed in #42
