### ISSUE TITLE
Add support for multiple `except-selector`s

### ISSUE THREAD

**Issue by dpatz** [zeppelin/ember-click-outside#38]
I have a popover that contains a form with a power select and another popover and need to add an `except-selector` for both.

Is there anyway we could do this now with the current functionality or is this something that would need to be added?

**Comment by zeppelin** [comment]
@dpatz Hey, sorry for the late response! 

You can do that today by writing something like: `except-selector=".some-class, .some-other-class"`, because any selector that can be passed to `document.querySelector()` could be used.

**Comment by dpatz** [comment]
Thanks, I'll try it out!

**Comment by zeppelin** [comment]
Np. Also, make sure you you're using `v1.0.1`, because the latest patch fixes an issue with how selectors are matched against the click event target!
