### ISSUE TITLE
Renaming component's callback on clickOutside

### ISSUE THREAD

**Issue by AndreJoaquim** [zeppelin/ember-click-outside#45]
Currently, extending this add-on's component feels like the following:
```javascript
import ClickOutsideComponent from 'ember-click-outside/component';

export default ClickOutsideComponent.extend({
  tagName: 'span',

  isOpen: true,
  
  /*
   * This is the function called by the ClickOutsideComponent on an outside click
   */
  action() {
    this.set('isOpen', false);
  }
});
```

However, I don't feel like `action` is a very self-explanatory name for this: it could mean literally **any** action. I'd like to suggest changing this to `onClickOutside` or allowing both, so we could keep backward-compatibility.

The final result would be something like:
```javascript
import ClickOutsideComponent from 'ember-click-outside/component';

export default ClickOutsideComponent.extend({
  tagName: 'span',

  isOpen: true,
  
  /*
   * This is the function called by the ClickOutsideComponent on an outside click
   * with a self-explanatory name
   */
  onClickOutside() {
    this.set('isOpen', false);
  }
});
```

What's your opinion on this?

**Comment by zeppelin** [comment]
@AndreJoaquim Actually I was playing with the same idea, but postponed until I can see how the whole thing could be implemented with the upcoming [Element Modifiers](https://github.com/emberjs/rfcs/blob/new-modifiers/text/0000-modifiers.md) and change it then.

But maybe you're right about the timing and it should be done now, then raise a deprecation warning starting from the next minor release.

Care to volunteer to implement it? :)

**Comment by AndreJoaquim** [comment]
@zeppelin I think implementing an element modifier would be pretty damn cool for the use-cases of this add-on :)

I'll try to see if I have some time this week to implement this and I'll open a PR when I have this ready. Cheers!

**Comment by zeppelin** [comment]
I've made some progress on the element modifier version, it works like charm! :)
https://github.com/zeppelin/ember-click-outside/tree/element-modifier

Didn't finish yet, but most likely will tomorrow!

**Comment by mattmcmanus** [comment]
@zeppelin I was just thinking about putting an element modifier version of this together. Do you need any help getting this across the finish line? This would improve the usability of the wonderful addon 10X

**Comment by zeppelin** [comment]
@mattmcmanus I have it ready, but wanted to check wait for the final modifiers spec. It's out now for a while, so nothing's holding back. Will do in the next few days!
