### ISSUE TITLE
Support for touch events?

### ISSUE THREAD

**Issue by DSheffield** [zeppelin/ember-click-outside#48]
Is there any plan to support touch events as well?  So click outside could effectively be click or touch outside?

**Comment by zeppelin** [comment]
@DSheffield It does work on mobile devices - if that's what you're asking. Is there a specific reason you need touch events?

**Comment by DSheffield** [comment]
I see from your simple demo app it does seem to work with touch (or at least the corresponding mouse events the browser sends when touches occur).  We've used the addon in our app and it seemed it wasn't invoking the clickOutside action in response to touch events.  But, maybe we've done something that's interfering with the events.  I'll check into that a bit further.

We're using touch screen laptops (not phones / ipads, etc).

**Comment by DSheffield** [comment]
So, here's an example of what we're looking to support. A simple touch / release triggers the action.  A touch / swipe, however, does not:

![touchOutside1](https://user-images.githubusercontent.com/6086162/54387613-3ae7da00-4672-11e9-9786-7d55166f9324.gif)

But a similar drag with the mouse does trigger the action:

![clickOutside1](https://user-images.githubusercontent.com/6086162/54387639-4cc97d00-4672-11e9-9761-ecc07c6ce37a.gif)

**Comment by zeppelin** [comment]
So you need the same click behavior on touch-based devices?

**Comment by DSheffield** [comment]
Yeah, effectively I want the clickOutside action to  be triggered any time there's any kind of touch interaction not within my component.

**Comment by zeppelin** [comment]
To be honest I did not have such goals :) Nevertheless, if you have working fork supporting this -and it does fit into the original addon's API- I'm happy to pull the changes to upstream!

**Comment by DSheffield** [comment]
What is your browser / version support goal?

**Comment by zeppelin** [comment]
@DSheffield Can be achieved with #51
