### ISSUE TITLE
Clicking inside component and releasing outside is closing the component. How do exclude this behavior?

### ISSUE THREAD

**Issue by kumkanillam** [zeppelin/ember-click-outside#49]
I got a very interesting issue here to discuss.
 
On clicking icon, I am opening submit issue component,

```
{{#if showSubmitIssue}}
{{#click-outside action=(action 'toggleSendEmailPane' false)}}	
   {{submit-issue }}      
{{/click-outside}}
{{/if}}
```

Clicking inside the submit issue component and releasing it outside submit-issue component is actually closing the submit-issue.

In this case, I don't want to close the submit-issue component. How do we achieve this?.
I have simply used `mousedown` event instead of `click` fixed it.

Is it worth to consider for PR or are there any other fixes is available for this issue?.

**Comment by zeppelin** [comment]
@kumkanillam thanks for reporting.

Changing `click` to `mousedown`, however, might fix your use case but will break everybody else's.

Try running the test suite - I'm 100% sure it'll break.

It isn't impossible to support the suggested behavior, it's merely more work, roughly:
1. When `mousedown` happens, see if it was inside the the component, plus register the result on the component
1. When `click` (the current handler) executes, check if the previous `mousedown` was originated from the outside. If so, perform the action.
1. See if it causes any issues on touch-based devices

**Comment by kumkanillam** [comment]
Thanks for providing option to specify the event type.  thanks much @crowjonah
