### ISSUE TITLE
implicit-modifier-manager-capabilities deprecation

### ISSUE THREAD

**Issue by timmorey** [zeppelin/ember-click-outside#56]
When running against ember 3.13, this addon is causing a runtime deprecation warning.  You can repro by simply using the `on-click-outside` modifier in an app.

It is also visible in the travis output: https://travis-ci.org/zeppelin/ember-click-outside/jobs/604459106#L1170

**Comment by zeppelin** [comment]
Fixed in #58. Sorry it took this long!
