### ISSUE TITLE
Use `capture: true` for event handler registration

### ISSUE THREAD

**Issue by Turbo87** [zeppelin/ember-click-outside#59]
I have roughly the following setup:

```hbs
<LinkTo>
  some text
  <button {{on "click" (stop-propagation this.handleButtonClick)}}></button>
  some other text
</LinkTo>
```

Clicking the button makes a dropdown appear, that uses the `on-click-outside` modifier.

The problem is that clicking that button uses `event.stopPropagation()`, which means that the `click` event never reaches the `document` node, so the `on-click-outside` behavior is never triggered.

If we would pass `{ capture: true }` to the `add/removeEventListener()` calls in the modifier this problem could be fixed because the `document` node would be the first to react to this event.

**Comment by zeppelin** [comment]
Hey @Turbo87, thanks for suggesting! I'll add it to the next minor release!

**Comment by Turbo87** [comment]
great, thank you!

since it could potentially break a few existing implementations I would consider doing it in a major version release though. since Node 8 will reach the end of its support cycle at the end of the month it might be good to combine those two breaking changes :)

**Comment by zeppelin** [comment]
I was thinking it should be explicit opt-in first

**Comment by Turbo87** [comment]
good idea, I think that should work 👍
