### ISSUE TITLE
behaviour differs between component and modifier version

### ISSUE THREAD

**Issue by st-h** [zeppelin/ember-click-outside#98]
I am using ember-click-outside to close modals and popups when the user clicks outside. The modifier version is very welcome as it does not introduce an additional dom element.

However, I noticed that I can not use the modifier version as its behaviour is different:

```
<button type="button" {{on 'click' (fn (mut this._showComponent))}}>open component</button>

{{#if this._showComponent}}
  <ClickOutside @onClickOutside={{fn (mut this._showComponent) false}}
     click below to hide
  </ClickOutside>
{{/if}}
```
This button just sets a variable to true, which renders an additional element, which should be closed when clicked outside. The code above works without issues.

This is the same code, but uses the modifier versions:
```
<button type="button" {{on 'click' (fn (mut this._showModifier))}}>open modifier</button>

{{#if this._showModifier}}
  <div {{on-click-outside (fn (mut this._showModifier) false)}}>
    click below to hide 
  </div>
{{/if}}
</section>
```
The issue here is that the `on-click-outside` modifier fires after the `on` modifier has fired, so the button shows the additional element, and `on-click-outside` hides it again, so the element never actually gets displayed. Seems like the modifier is added while the click is in progress and the out-side-click handler picks up the click that is supposed to make the element visible.

This repo https://github.com/st-h/ember-click-outside-test contains a demo app with both examples.

It might help if we schedule the installation of the handler on the event loop. But I am not totally sure if this will solve all issues.

To workaround this, one could change the eventType:
```
<div {{on-click-outside (fn (mut this._showModifier) false) eventType='mouseup'}}>
```
However, this only defers the issue, as it would pop up again if the event the button listens on changes.

**Comment by zeppelin** [comment]
@st-h Thanks for reporting, I'll take a look at it!

**Comment by zeppelin** [comment]
@st-h Probably related: https://github.com/zeppelin/ember-click-outside/pull/71

**Comment by st-h** [comment]
> @st-h Probably related: #71

Thank you. Partially definitely related. I can fix the initial issue adding `capture=true`.
However, if I try to toggle using the button, I end up in a situation where the modifier version does not hide the element, when the button is hit again. Component version works without issues. I have modified above reproducer repo.

```
  <section>
    <button type="button" {{on 'click' (fn this.toggleModifier)}}>open modifier</button>

    <div>_showModifier: {{this._showModifier}}</div>
    {{#if this._showModifier}}
      <div {{on-click-outside (fn (mut this._showModifier) false) capture=true}}>
        click below to hide
      </div>
    {{/if}}
  </section>
```

**Comment by zeppelin** [comment]
@st-h could you please test `v1.4.0-beta.0`? I've updated the modifier to match the component's behavior. I'll release if it works, along with tools for testing.

**Comment by st-h** [comment]
Sorry about the late reply. I haven't had any time to migrate old code, but as far I have tried it when writing new components, everything seemed to work great using the new version. 👍
